### ISSUE TITLE
Unexpected HTTP response mimetype: text/html; charset=utf-8

### ISSUE THREAD

**Issue by 31z4** [FactomProject/fctwallet#1]
`Content-Type` for every fctwallet's HTTP response containing JSON should be `application/json`.

**Comment by hannemennah** [comment]
This should be fixed with [this commit](https://github.com/FactomProject/fctwallet/commit/f13242575e9507807465850b6d644b5574dc610f), currently on Hotfix5 branch.

If you notice the problem occur again in any context or situation, please let me know specifically how to replicate it, if at all possible.
