### ISSUE TITLE
Page not found 8089

### ISSUE THREAD

**Issue by jlucid** [FactomProject/fctwallet#3]
Hi there,

I have setup a local sandbox factomd server (Windows) using  "factomd -network=LOCAL" command
and have added the factomd.conf file as given here 
https://raw.githubusercontent.com/FactomProject/FactomCode/master/factomd/factomd.conf

I have been able to create entry credits from factoids in the fctwallet using the command
 factom-cli buyec [-fqrT] FCTADDRESS ECADDRESS ECAMOUNT
so everything is going well so far, except none of the API calls to my wallet (8089) are working.

"Page not found" example is shown below..

// Command line client tool indicates wallet is up
C:\Program Files\Factom>factom-cli properties 
CLI Version: 0.2.0.2
Factomd Version: 0.4.0.2
Factomd API Version: 2.0
Wallet Version: 0.2.0.2
Wallet API Version: 2.0

// API requests to factomd are returning as expected
C:\Program Files\Factom>curl -X GET "http://localhost:8088/v1/properties/"  
{"Protocol_Version":"0.0.0.0","Factomd_Version":"0.4.0.2"}

// Command line client tool retrieves wallet factoid balance correctly
C:\Program Files\Factom>factom-cli balance -r     FA1zT4aFpEvcnPqPCigB3fvGu4Q4mTXY22iiuV69DqE1pNhdF2MC
19999.99978

**** Always getting a 'Page not found' error with API requests to wallet"
C:\Program Files\Factom>curl -X GET "http://localhost:8089/v1/factoid-balance/FA1zT4aFpEvcnPqPCigB3fvGu4Q4mTXY22iiuV69DqE1pNhdF2MC"
Page not found

Note: When the above command is run, I am seeing output on the fctwallet interactive log
2017/02/26 16:56:06 [::1] - [32;1m GET /v1/factoid-balance/FA1zT4aFpEvcnPqPCigB3fvGu4Q4mTXY22iiuV69DqE1pNhdF2MC[0m - 504µs
but nothing being returned..

Any idea what could be going on here or how I could troubleshoot?

Many thanks,

**Comment by carryforward** [comment]
How tied are you to using fctwallet?  It is pretty much unsupported at this point.  While technically it works, it is extremely slow to make some calls. every time fctwallet starts, it pulls all factoid blocks from the factomd instance.  For some reason this is a multi-hour process in m2 instead of a few minutes in m1.

The API wallet we are building on going forward is factom-walletd.  It caches the factoid blocks, so it doesn't have lots of overhead when it starts up.  you can see that fctwallet is still booting by seeing the continuation of v1 calls to factomd.

If you wanted to use factom-cli with fctwallet, you should use the old version: factom-cli1.  the latest version of factom-cli does not talk to fctwallet.

https://github.com/FactomProject/FactomDocs/blob/master/legacyWallets.md

**Comment by carryforward** [comment]
here is some documentation of the wallet API:
https://docs.factom.com/api#factom-walletd-api

**Comment by jlucid** [comment]
Thank you. Info has been very useful.
I am now using the factom-walletd and it is working well. API calls from the doc page you passed me are returning as expected.  

So can I just ignore the below factoid-api guide in place of the newer one?
https://www.factom.com/devs/docs/guide/factoid-api-reference 

Cheers
